Traceback (most recent call last):
  File "/home/tonu/Documents/apps/dashboard_invest/dashboard/logic/io.py", line 858, in wrapper
    result = func(ddf)
             ^^^^^^^^^
  File "/tmp/ipykernel_344186/1397505668.py", line 10, in forecasts_script
    ddfs = ddf.getDdfDict({
           ^^^^^^^^^^^^^^^^
  File "/home/tonu/Documents/apps/dashboard_invest/dashboard/logic/io.py", line 131, in getDdfDict
    row_i, col_i = get_reference_row_col_idx(df, pattern=v[1], method=v[0])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonu/Documents/apps/dashboard_invest/dashboard/logic/io.py", line 81, in get_reference_row_col_idx
    return index[0], column[0]
           ~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
