Traceback (most recent call last):
  File "/tmp/ipykernel_344186/4200741089.py", line 123, in wrapper
    result = func(ddf)
             ^^^^^^^^^
  File "/tmp/ipykernel_344186/810289797.py", line 240, in forecasts_script
    ddfs = ddf.getDdfDict({
           ^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_344186/810289797.py", line 112, in getDdfDict
    row_i, col_i = get_reference_row_col_idx(df, pattern=v[1], method=v[0])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_344186/810289797.py", line 61, in get_reference_row_col_idx
    return index[0], column[0]
           ~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
